# Generated by Django 3.1.4 on 2021-01-26 16:26

from django.db import migrations, models

import targets.models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(upload_to=targets.models.image_name),
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
