# Generated by Django 3.1.4 on 2021-02-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_auto_20210126_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
